hobocta_portfolio_homepage:
    path:     /
    defaults: { _controller: HoboctaPortfolioBundle:Default:index }

hobocta_portfolio_work:
    path:     /{code}.html
    defaults: { _controller: HoboctaPortfolioBundle:Work:show }
    requirements:
      methods: GET
      code:    '[a-z0-9-]+'
